tests: Move functional tests to 'tests' module.
Tested with:

PASSES="fmt functional unit" ./test
make build-docker-functional

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source ./scripts/test_lib.sh
+
 # set some environment variables
 ORG_PATH="go.etcd.io"
 REPO_PATH="${ORG_PATH}/etcd/v3"
@@ -16,9 +18,9 @@ GO_LDFLAGS="$GO_LDFLAGS -X ${REPO_PATH}/version.GitSHA=${GIT_SHA}"
 toggle_failpoints() {
 	mode="$1"
 	if command -v gofail >/dev/null 2>&1; then
-		gofail "$mode" etcdserver/ mvcc/backend/
+		run gofail "$mode" etcdserver/ mvcc/backend/
 	elif [[ "$mode" != "disable" ]]; then
-		echo "FAILPOINTS set but gofail not found"
+		log_error "FAILPOINTS set but gofail not found"
 		exit 1
 	fi
 }
@@ -36,37 +38,56 @@ etcd_build() {
 
 	# Static compilation is useful when etcd is run in a container. $GO_BUILD_FLAGS is OK
 	# shellcheck disable=SC2086
-	CGO_ENABLED=0 go build $GO_BUILD_FLAGS \
-		-installsuffix cgo \
-		-ldflags "$GO_LDFLAGS" \
-		-o "${out}/etcd" ${REPO_PATH} || return
+	CGO_ENABLED=0 run go build $GO_BUILD_FLAGS \
+		-installsuffix=cgo \
+		"-ldflags='${GO_LDFLAGS}'" \
+		-o="${out}/etcd" . || return
 	# shellcheck disable=SC2086
-	CGO_ENABLED=0 go build $GO_BUILD_FLAGS \
-		-installsuffix cgo \
-		-ldflags "$GO_LDFLAGS" \
-		-o "${out}/etcdctl" ${REPO_PATH}/etcdctl || return
+	CGO_ENABLED=0 run go build $GO_BUILD_FLAGS \
+		-installsuffix=cgo \
+		"-ldflags='${GO_LDFLAGS}'" \
+		-o="${out}/etcdctl" ./etcdctl || return
 }
 
 tools_build() {
 	out="bin"
 	if [[ -n "${BINDIR}" ]]; then out="${BINDIR}"; fi
 	tools_path="tools/benchmark
-	tools/etcd-dump-db
-	tools/etcd-dump-logs
-	tools/local-tester/bridge
-	functional/cmd/etcd-agent
-	functional/cmd/etcd-proxy
-	functional/cmd/etcd-runner
-	functional/cmd/etcd-tester"
+		tools/etcd-dump-db
+		tools/etcd-dump-logs
+		tools/local-tester/bridge"
 	for tool in ${tools_path}
 	do
 		echo "Building" "'${tool}'"...
 		# shellcheck disable=SC2086
-		CGO_ENABLED=0 go build ${GO_BUILD_FLAGS} \
-		  -installsuffix cgo \
-		  -ldflags "${GO_LDFLAGS}" \
-		  -o "${out}/${tool}" "${REPO_PATH}/${tool}" || return
+		CGO_ENABLED=0 run go build ${GO_BUILD_FLAGS} \
+		  -installsuffix=cgo \
+		  "-ldflags='${GO_LDFLAGS}'" \
+		  -o="${out}/${tool}" "./${tool}" || return
 	done
+	tests_build "${@}"
+}
+
+tests_build() {
+	out="bin"
+	if [[ -n "${BINDIR}" ]]; then out="${BINDIR}"; fi
+	tools_path="
+		functional/cmd/etcd-agent
+		functional/cmd/etcd-proxy
+		functional/cmd/etcd-runner
+		functional/cmd/etcd-tester"
+	(
+		cd tests || exit 2
+		for tool in ${tools_path}; do
+			echo "Building" "'${tool}'"...
+
+			# shellcheck disable=SC2086
+			CGO_ENABLED=0 run go build ${GO_BUILD_FLAGS} \
+			  -installsuffix=cgo \
+			  "-ldflags='${GO_LDFLAGS}'" \
+			  -o="../${out}/${tool}" "./${tool}" || return
+    		done
+	)
 }
 
 toggle_failpoints_default
diff --git a/test b/test
--- a/test
+++ b/test
@@ -137,11 +137,12 @@ function generic_checker {
 }
 
 function functional_pass {
-  ./functional/build
+  run ./tests/functional/build
 
   # Clean up any data and logs from previous runs
   rm -rf /tmp/etcd-functional-* /tmp/etcd-functional-*.backup
 
+  # TODO: These ports should be dynamically allocated instead of hard-coded.
   for a in 1 2 3; do
     ./bin/etcd-agent --network tcp --address 127.0.0.1:${a}9027 &
     pid="$!"
@@ -149,22 +150,25 @@ function functional_pass {
   done
 
   for a in 1 2 3; do
-    echo "Waiting for 'etcd-agent' on ${a}9027..."
+    log_callout "Waiting for 'etcd-agent' on ${a}9027..."
     while ! nc -z localhost ${a}9027; do
       sleep 1
     done
   done
 
-  echo "functional test START!"
-  run ./bin/etcd-tester --config ./functional.yaml && log_success "'etcd-tester' succeeded"
-  ETCD_TESTER_EXIT_CODE=$?
-  echo "ETCD_TESTER_EXIT_CODE:" ${ETCD_TESTER_EXIT_CODE}
+  log_callout "functional test START!"
+  run ./bin/etcd-tester --config ./tests/functional/functional.yaml && log_success "'etcd-tester' succeeded"
+  local etcd_tester_exit_code=$?
+
+  if [[ "${etcd_tester_exit_code}" -ne "0" ]]; then
+    log_error "ETCD_TESTER_EXIT_CODE:" ${etcd_tester_exit_code}
+  fi
 
   # shellcheck disable=SC2206
   agent_pids=($agent_pids)
   kill -s TERM "${agent_pids[@]}" || true
 
-  if [[ "${ETCD_TESTER_EXIT_CODE}" -ne "0" ]]; then
+  if [[ "${etcd_tester_exit_code}" -ne "0" ]]; then
     log_error -e "\nFAILED! 'tail -1000 /tmp/etcd-functional-1/etcd.log'"
     tail -1000 /tmp/etcd-functional-1/etcd.log
 
@@ -174,8 +178,8 @@ function functional_pass {
     log_error -e "\nFAILED! 'tail -1000 /tmp/etcd-functional-3/etcd.log'"
     tail -1000 /tmp/etcd-functional-3/etcd.log
 
-    log_error "--- FAIL: exit code" ${ETCD_TESTER_EXIT_CODE}
-    return ${ETCD_TESTER_EXIT_CODE}
+    log_error "--- FAIL: exit code" ${etcd_tester_exit_code}
+    return ${etcd_tester_exit_code}
   fi
   log_success "functional test PASS!"
 }
