test: add govet to tests

diff --git a/test b/test
--- a/test
+++ b/test
@@ -49,4 +49,11 @@ if [ -n "${fmtRes}" ]; then
 	exit 255
 fi
 
+echo "Checking govet..."
+vetRes=$(go vet $TEST)
+if [ -n "${vetRes}" ]; then
+	echo -e "govet checking failed:\n${vetRes}"
+	exit 255
+fi
+
 echo "Success"
