robustness/e2e: blackhole both inbound and outbound peer traffic
Ref: https://github.com/etcd-io/etcd/issues/17737

Signed-off-by: Chun-Hung Tseng <henrytseng@google.com>

diff --git a/tests/robustness/Makefile b/tests/robustness/Makefile
--- a/tests/robustness/Makefile
+++ b/tests/robustness/Makefile
@@ -80,14 +80,29 @@ test-robustness-issue20221-fix20229-resumable: /tmp/etcd-bc47e771-failpoints/bin
 	GO_TEST_FLAGS='-v --run=TestRobustnessRegression/Issue20221_fix20229_resumable --count 100 --failfast --bin-dir=/tmp/etcd-bc47e771-failpoints/bin' $(TOPLEVEL_MAKE) test-robustness && \
 	 echo "Failed to reproduce" || echo "Successful reproduction"
 
+.PHONY: test-robustness-issue20221-fix20229-resumable-peer-partition
+test-robustness-issue20221-fix20229-resumable-peer-partition: /tmp/etcd-bc47e771-peerProxyMap-failpoints/bin
+	GO_TEST_FLAGS='-v --run=TestRobustnessRegression/Issue20221_fix20229_resumable_PeerPartition --count 100 --failfast --bin-dir=/tmp/etcd-bc47e771-peerProxyMap-failpoints/bin' $(TOPLEVEL_MAKE) test-robustness && \
+	 echo "Failed to reproduce" || echo "Successful reproduction"
+
 .PHONY: test-robustness-issue20221-fix20229-bookmarkable
 test-robustness-issue20221-fix20229-bookmarkable: /tmp/etcd-bc47e771-patch-failpoints/bin
 	GO_TEST_FLAGS='-v --run=TestRobustnessRegression/Issue20221_fix20229_bookmarkable --count 100 --failfast --bin-dir=/tmp/etcd-bc47e771-patch-failpoints/bin' $(TOPLEVEL_MAKE) test-robustness && \
 	 echo "Failed to reproduce" || echo "Successful reproduction"
 
+.PHONY: test-robustness-issue20221-fix20229-bookmarkable-peer-partition
+test-robustness-issue20221-fix20229-bookmarkable-peer-partition: /tmp/etcd-bc47e771-patch-peerProxyMap-failpoints/bin
+	GO_TEST_FLAGS='-v --run=TestRobustnessRegression/Issue20221_fix20229_bookmarkable_PeerPartition --count 100 --failfast --bin-dir=/tmp/etcd-bc47e771-patch-peerProxyMap-failpoints/bin' $(TOPLEVEL_MAKE) test-robustness && \
+	 echo "Failed to reproduce" || echo "Successful reproduction"
+
 .PHONY: test-robustness-issue20221-fix20281
 test-robustness-issue20221-fix20281: /tmp/etcd-44a094a2-failpoints/bin
 	GO_TEST_FLAGS='-v --run=TestRobustnessRegression/Issue20221_fix20281 --count 100 --failfast --bin-dir=/tmp/etcd-44a094a2-failpoints/bin' $(TOPLEVEL_MAKE) test-robustness && \
+	 echo "Failed to reproduce" || echo "Successful reproduction"
+
+.PHONY: test-robustness-issue20221-fix20281-peer-partition
+test-robustness-issue20221-fix20281-peer-partition: /tmp/etcd-44a094a2-peerProxyMap-failpoints/bin
+	GO_TEST_FLAGS='-v --run=TestRobustnessRegression/Issue20221_fix20281_PeerPartition --count 100 --failfast --bin-dir=/tmp/etcd-44a094a2-peerProxyMap-failpoints/bin' $(TOPLEVEL_MAKE) test-robustness && \
 	 echo "Failed to reproduce" || echo "Successful reproduction"
 
 # Etcd API usage by Kubernetes
@@ -169,6 +184,34 @@ $(GOPATH)/bin/gofail: $(REPOSITORY_ROOT)/tools/mod/go.mod $(REPOSITORY_ROOT)/too
 	  $(MAKE) gofail-enable && \
 	  $(MAKE) build
 
+/tmp/etcd-bc47e771-peerProxyMap-failpoints/bin: $(GOPATH)/bin/gofail
+	rm -rf /tmp/etcd-bc47e771-peerProxyMap-failpoints/
+	mkdir -p /tmp/etcd-bc47e771-peerProxyMap-failpoints/
+	cd /tmp/etcd-bc47e771-peerProxyMap-failpoints/ && \
+	  git init && \
+	  git remote add origin https://github.com/etcd-io/etcd.git && \
+	  git fetch --depth 1 origin bc47e7711664ec5557c5ae528d0d02175ea6e166 && \
+	  git checkout FETCH_HEAD && \
+	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/peerProxyMap . && \
+	  patch -l server/etcdserver/api/rafthttp/util.go ./peerProxyMap/util.patch && \
+	  $(MAKE) gofail-enable && \
+	  $(MAKE) build
+
+/tmp/etcd-bc47e771-patch-peerProxyMap-failpoints/bin: $(GOPATH)/bin/gofail
+	rm -rf /tmp/etcd-bc47e771-patch-peerProxyMap-failpoints/
+	mkdir -p /tmp/etcd-bc47e771-patch-peerProxyMap-failpoints/
+	cd /tmp/etcd-bc47e771-patch-peerProxyMap-failpoints/ && \
+	  git init && \
+	  git remote add origin https://github.com/etcd-io/etcd.git && \
+	  git fetch --depth 1 origin bc47e7711664ec5557c5ae528d0d02175ea6e166 && \
+	  git checkout FETCH_HEAD && \
+	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/closeWatchStream . && \
+	  patch --fuzz=0 server/etcdserver/api/v3rpc/watch.go ./closeWatchStream/watch.patch && \
+	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/peerProxyMap . && \
+	  patch -l server/etcdserver/api/rafthttp/util.go ./peerProxyMap/util.patch && \
+	  $(MAKE) gofail-enable && \
+	  $(MAKE) build
+
 /tmp/etcd-44a094a2-failpoints/bin: $(GOPATH)/bin/gofail
 	rm -rf /tmp/etcd-44a094a2-failpoints/
 	mkdir -p /tmp/etcd-44a094a2-failpoints/
@@ -181,6 +224,23 @@ $(GOPATH)/bin/gofail: $(REPOSITORY_ROOT)/tools/mod/go.mod $(REPOSITORY_ROOT)/too
 	  patch --fuzz=0 server/etcdserver/api/v3rpc/watch.go ./closeWatchStream/watch.patch && \
 	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/removeVerifyModRevision . && \
 	  patch --fuzz=0 server/storage/mvcc/watchable_store.go ./removeVerifyModRevision/watchable_store.patch && \
+	  $(MAKE) gofail-enable && \
+	  $(MAKE) build
+
+/tmp/etcd-44a094a2-peerProxyMap-failpoints/bin: $(GOPATH)/bin/gofail
+	rm -rf /tmp/etcd-44a094a2-peerProxyMap-failpoints/
+	mkdir -p /tmp/etcd-44a094a2-peerProxyMap-failpoints/
+	cd /tmp/etcd-44a094a2-peerProxyMap-failpoints/ && \
+	  git init && \
+	  git remote add origin https://github.com/etcd-io/etcd.git && \
+	  git fetch --depth 1 origin 44a094a20a7a0ac16cf88c9f21b6ca90e9f85cf5 && \
+	  git checkout FETCH_HEAD && \
+	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/closeWatchStream . && \
+	  patch --fuzz=0 server/etcdserver/api/v3rpc/watch.go ./closeWatchStream/watch.patch && \
+	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/removeVerifyModRevision . && \
+	  patch --fuzz=0 server/storage/mvcc/watchable_store.go ./removeVerifyModRevision/watchable_store.patch && \
+	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/peerProxyMap . && \
+	  patch -l server/etcdserver/api/rafthttp/util.go ./peerProxyMap/util.patch && \
 	  $(MAKE) gofail-enable && \
 	  $(MAKE) build
 
