Add robustness test scenario for issue #20221 (fix #20281)
There is an issue with the `ETCD_VERIFY` causing
`panic: Event.ModRevision(1083) is less than the w.startRev(1170) for watchID: 0 [recovered]`
during the test. It's great that we have reproduction, but it's sad
that it will hang the test with a never-ending printing of
`dropped internal Raft message since sending buffer is full`.

In order to let the test finish normally and let the watch validator
perform its check, a patch to disable this check is created and applied
when test-robustness-issue20221-fix20281 is being executed (since it's
the only commit in the series of 20221 fixes that contains this
verification check).

Signed-off-by: Chun-Hung Tseng <henrytseng@google.com>

diff --git a/tests/robustness/Makefile b/tests/robustness/Makefile
--- a/tests/robustness/Makefile
+++ b/tests/robustness/Makefile
@@ -85,6 +85,11 @@ test-robustness-issue20221-fix20229-bookmarkable: /tmp/etcd-bc47e771-patch-failp
 	GO_TEST_FLAGS='-v --run=TestRobustnessRegression/Issue20221_fix20229_bookmarkable --count 100 --failfast --bin-dir=/tmp/etcd-bc47e771-patch-failpoints/bin' $(TOPLEVEL_MAKE) test-robustness && \
 	 echo "Failed to reproduce" || echo "Successful reproduction"
 
+.PHONY: test-robustness-issue20221-fix20281
+test-robustness-issue20221-fix20281: /tmp/etcd-44a094a2-failpoints/bin
+	GO_TEST_FLAGS='-v --run=TestRobustnessRegression/Issue20221_fix20281 --count 100 --failfast --bin-dir=/tmp/etcd-44a094a2-failpoints/bin' $(TOPLEVEL_MAKE) test-robustness && \
+	 echo "Failed to reproduce" || echo "Successful reproduction"
+
 # Etcd API usage by Kubernetes
 
 .PHONY: k8s-coverage
@@ -161,6 +166,21 @@ $(GOPATH)/bin/gofail: $(REPOSITORY_ROOT)/tools/mod/go.mod $(REPOSITORY_ROOT)/too
 	  git checkout FETCH_HEAD && \
 	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/closeWatchStream . && \
 	  patch --fuzz=0 server/etcdserver/api/v3rpc/watch.go ./closeWatchStream/watch.patch && \
+	  $(MAKE) gofail-enable && \
+	  $(MAKE) build
+
+/tmp/etcd-44a094a2-failpoints/bin: $(GOPATH)/bin/gofail
+	rm -rf /tmp/etcd-44a094a2-failpoints/
+	mkdir -p /tmp/etcd-44a094a2-failpoints/
+	cd /tmp/etcd-44a094a2-failpoints/ && \
+	  git init && \
+	  git remote add origin https://github.com/etcd-io/etcd.git && \
+	  git fetch --depth 1 origin 44a094a20a7a0ac16cf88c9f21b6ca90e9f85cf5 && \
+	  git checkout FETCH_HEAD && \
+	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/closeWatchStream . && \
+	  patch --fuzz=0 server/etcdserver/api/v3rpc/watch.go ./closeWatchStream/watch.patch && \
+	  cp -r $(REPOSITORY_ROOT)/tests/robustness/patches/removeVerifyModRevision . && \
+	  patch --fuzz=0 server/storage/mvcc/watchable_store.go ./removeVerifyModRevision/watchable_store.patch && \
 	  $(MAKE) gofail-enable && \
 	  $(MAKE) build
 
