script: Build docker image for ppc64le

diff --git a/scripts/build-docker b/scripts/build-docker
--- a/scripts/build-docker
+++ b/scripts/build-docker
@@ -1,5 +1,32 @@
 #!/usr/bin/env bash
 
+if [ "$#" -ne 1 ]; then
+	echo "Usage: $0 VERSION" >&2
+	exit 1
+fi
+
+ARCH=$(go env GOARCH)
+DOCKERFILE="Dockerfile-release"
+TAG="quay.io/coreos/etcd"
+
+if [ -z ${BINARYDIR} ]; then
+	RELEASE="etcd-${1}"-`go env GOOS`-`go env GOARCH`
+	BINARYDIR="${RELEASE}"
+	TARFILE="${RELEASE}.tar.gz"
+	TARURL="https://github.com/coreos/etcd/releases/download/${1}/${TARFILE}"
+	curl -f -L -o ${TARFILE} ${TARURL}
+	if [ $? != 0 ]; then
+		echo "Failed to download ${TARURL}."
+		exit 1
+	fi
+	tar -zvxf ${TARFILE}
+fi
+
+if [ ${ARCH} != "amd64" ]; then
+	DOCKERFILE+=".${ARCH}"
+	TAG+="-${ARCH}"
+fi
+
 BINARYDIR=${BINARYDIR:-.}
 BUILDDIR=${BUILDDIR:-.}
 
@@ -8,6 +35,6 @@ IMAGEDIR=${BUILDDIR}/image-docker
 mkdir -p ${IMAGEDIR}
 cp ${BINARYDIR}/etcd ${BINARYDIR}/etcdctl ${IMAGEDIR}
 
-cat ./Dockerfile-release > ${IMAGEDIR}/Dockerfile
+cat ./${DOCKERFILE} > ${IMAGEDIR}/Dockerfile
 
-docker build -t quay.io/coreos/etcd:${1} ${IMAGEDIR}
+docker build -t ${TAG}:${1} ${IMAGEDIR}
