ci: Introduce yamllint for actions workflow files
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

diff --git a/.github/workflows/grpcproxy.yaml b/.github/workflows/grpcproxy.yaml
--- a/.github/workflows/grpcproxy.yaml
+++ b/.github/workflows/grpcproxy.yaml
@@ -1,3 +1,4 @@
+---
 name: grpcProxy-tests
 on: [push, pull_request]
 permissions: read-all
@@ -11,29 +12,29 @@ jobs:
       fail-fast: true
       matrix:
         target:
-        - linux-amd64-grpcproxy-integration
-        - linux-amd64-grpcproxy-e2e
+          - linux-amd64-grpcproxy-integration
+          - linux-amd64-grpcproxy-e2e
     steps:
-    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
-    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
-      with:
-        go-version: ${{ needs.goversion.outputs.goversion }}
-    - run: date
-    - env:
-        TARGET: ${{ matrix.target }}
-      run: |
-        set -euo pipefail
+      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
+      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
+        with:
+          go-version: ${{ needs.goversion.outputs.goversion }}
+      - run: date
+      - env:
+          TARGET: ${{ matrix.target }}
+        run: |
+          set -euo pipefail
 
-        echo "${TARGET}"
-        case "${TARGET}" in
-          linux-amd64-grpcproxy-integration)
-            GOOS=linux GOARCH=amd64 CPU=4 RACE=true make test-grpcproxy-integration
-            ;;
-          linux-amd64-grpcproxy-e2e)
-            GOOS=linux GOARCH=amd64 CPU=4 RACE=true make test-grpcproxy-e2e
-            ;;
-          *)
-            echo "Failed to find target"
-            exit 1
-            ;;
-        esac
+          echo "${TARGET}"
+          case "${TARGET}" in
+            linux-amd64-grpcproxy-integration)
+              GOOS=linux GOARCH=amd64 CPU=4 RACE=true make test-grpcproxy-integration
+              ;;
+            linux-amd64-grpcproxy-e2e)
+              GOOS=linux GOARCH=amd64 CPU=4 RACE=true make test-grpcproxy-e2e
+              ;;
+            *)
+              echo "Failed to find target"
+              exit 1
+              ;;
+          esac
diff --git a/.github/workflows/robustness-template.yaml b/.github/workflows/robustness-template.yaml
--- a/.github/workflows/robustness-template.yaml
+++ b/.github/workflows/robustness-template.yaml
@@ -1,3 +1,4 @@
+---
 name: Reusable Robustness Workflow
 on:
   workflow_call:
@@ -28,37 +29,37 @@ jobs:
     runs-on: ${{ fromJson(inputs.runs-on) }}
     needs: goversion
     steps:
-    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
-    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
-      with:
-        go-version: ${{ needs.goversion.outputs.goversion }}
-    - name: test-robustness
-      env:
-        ETCD_BRANCH: "${{ inputs.etcdBranch }}"
-      run: |
-        set -euo pipefail
+      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
+      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
+        with:
+          go-version: ${{ needs.goversion.outputs.goversion }}
+      - name: test-robustness
+        env:
+          ETCD_BRANCH: "${{ inputs.etcdBranch }}"
+        run: |
+          set -euo pipefail
 
-        # Use --failfast to avoid overriding report generated by failed test
-        GO_TEST_FLAGS="-v --count ${{ inputs.count }} --timeout ${{ inputs.testTimeout }} --failfast --run TestRobustness"
-        case "${ETCD_BRANCH}" in
-          release-3.5)
-            EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.5
-            ;;
-          release-3.4)
-            EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.4
-            ;;
-          main)
-            make gofail-enable
-            make build
-            EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness
-            ;;
-          *)
-            echo "Failed to find target ${ETCD_BRANCH}"
-            exit 1
-            ;;
-        esac
-    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
-      if: always()
-      with:
-        name: ${{ inputs.artifactName }}
-        path: /tmp/results/*
+          # Use --failfast to avoid overriding report generated by failed test
+          GO_TEST_FLAGS="-v --count ${{ inputs.count }} --timeout ${{ inputs.testTimeout }} --failfast --run TestRobustness"
+          case "${ETCD_BRANCH}" in
+            release-3.5)
+              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.5
+              ;;
+            release-3.4)
+              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.4
+              ;;
+            main)
+              make gofail-enable
+              make build
+              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness
+              ;;
+            *)
+              echo "Failed to find target ${ETCD_BRANCH}"
+              exit 1
+              ;;
+          esac
+      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
+        if: always()
+        with:
+          name: ${{ inputs.artifactName }}
+          path: /tmp/results/*
